name: Render Deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Render Deployment
        uses: timc1/render-deploy-action@v1.0
        with:
          render-api-key: ${{secrets.API_KEY}}
          render-service-id: ${{secrets.SERVICE}}



